allprojects {
    repositories {
        maven { url "https://maven.aliyun.com/repository/google" }
        maven { url "https://maven.aliyun.com/repository/public" }
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

subprojects { subproject ->
    tasks.configureEach { task ->
        if (task.hasProperty("kotlinOptions")) {
            def kotlinJvmTarget = "17"
            if (subproject.name in ["receive_sharing_intent", "share_plus"]) {
                kotlinJvmTarget = "1.8"
            } else if (subproject.name == "speech_to_text") {
                kotlinJvmTarget = "11"
            }
            task.kotlinOptions.jvmTarget = kotlinJvmTarget
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
